name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-java
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Lint & Build with Gradle
      run: ./gradlew lintKotlin lint build

    - name: Run Unit Tests
      run: ./gradlew test

# NOTE: XML validation using node workflow is moved to `validations.yml` file.