name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew lint build

    - name: Run Unit Tests
      run: ./gradlew test

#
# This is experimental section to showcase multiple environments like JDK, Node, etc
# can be mixed together to have greater control in the CI environment.
#
# In this example, we activate Node on CI, install a Node module using npm
# and validate `AndroidManifest.xml` file as proof-of-concept (not required for Android dev).
#
# See technical article on Medium.com
# - https://medium.com/@hossainkhan/use-node-js-tools-on-github-actions-ci-workflow-120fb3b4a3e1
#
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install XML Validator
      run: npm install -g fast-xml-parser
    - name: Validate AndroidManifest.xml
      run: xml2js -V app/src/main/AndroidManifest.xml